### ISSUE TITLE
請問social icon 怎麼添加？與menu icon

### ISSUE THREAD

**Issue by s2339956** [shenliyang/hexo-theme-snippet#152]
```
menu:
- page: home
  url: /
  icon: icons8-home-page-80.png

## 社交设置{@name:社交工具名字，@icon:社交工具图标，@href:设置工具链接} [参考图标](http://fontawesome.io/icons/)
social:
  - name: Github
    icon: git
    href: //github.com/shenliyang
```

這兩個區域嘗試添加都無法顯示，請問作者該如何添加呢？
