### ISSUE TITLE
The widget "social" is unavailable

### ISSUE THREAD

**Issue by VictorZhang2014** [shenliyang/hexo-theme-snippet#4]
This is a part of configuration of the theme's `_config.yml`

```
## widgets
widgets:
- social
- notification
- category
- archive
- tagcloud
- friends

social:
 - name: Github
   icon: git
   href: //github.com/shenliyang
 - name: 邮箱
   icon: envelope-o
   href: mailto:snippet@91h5.cc
 - name: 联系QQ
   icon: qq
   href: /
 - name: 微博
   icon: weibo
   href: /
 - name: QQ群
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml
```

When running in Terminal, it occurred errors  as follows
```
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
WARN  Partial _widget/social does not exist. (in _partial/sidebar.ejs)
```

How do I do?
Thank you
