### ISSUE TITLE
怎样添加categories和tags页面

### ISSUE THREAD

**Issue by poorpool** [shenliyang/hexo-theme-snippet#55]
![pic1](https://i.loli.net/2018/06/11/5b1e2481a9a3b.png)

如图，我试图添加categories，然后失败了（没有达到`themes/snippet/layout/page.ejs`那里头描述的效果）

站点config：
```yaml
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
````

主题config：
```yaml
menu:
- page: home
  url: /
  icon:
- page: 关于
  url: /about
  icon:
- page: 公告留言板
  url: /board
  icon: 
- page: 分类
  url: /categories
  icon:
- page: 标签
  url: /tags
  icon: 
```

categories下的index.md
```yaml
---
title: categories
date: 2018-06-11 14:35:32
type: "categories"
layout: "page"
---
```
