### ISSUE TITLE
归档无法设置为“年类型yearly”

### ISSUE THREAD

**Issue by JiBaoBao** [shenliyang/hexo-theme-snippet#81]
楼主您好，归档类型默认为月类型'monthly'，我想将其设置成为年类型，我参照了`https://hexo.io/zh-cn/docs/helpers.html#list-archives*/`文档中，把对应参数设置为`yearly`
主题配置设置如下：
```
## 文章归档设置{@arch_config:/*参数参考：https://hexo.io/zh-cn/docs/helpers.html#list-archives*/}
arch_config:
   type: 'yearly'
   show_count: true
   order: -1
```
然后显示的还是月类型样式
